import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Your S1-S9 Episode Data
data = {
    "S1": [8.1, 8.4, 8.2, 8.4, 8.7, 8.3, 8.8, 8.5, 9.2, 9.1, 8.8, 8.8, None, None, None, None, None],
    "S2": [8.8, 8.4, 8.3, 8.2, 8.1, 8.8, 8.6, 8.1, 8.5, 8.2, 8.6, 8.5, None, None, None, None, None],
    "S3": [8.1, 8.3, 8.3, 8.6, 8.2, 8.3, 8.6, 8.2, 7.9, 8.3, 8.2, 8.9, None, None, None, None, None],
    "S4": [8.8, 8.6, 8.4, 8.9, 8.7, 8.3, 8.8, 8.5, 9.2, 9.1, 9.2, 9.3, 9.7, None, None, None, None],
    "S5": [8.1, 8.4, 8.2, 8.4, 8.7, 8.3, 8.8, 8.5, 9.2, 9.1, 8.4, 8.2, None, None, None, None, None],
    "S6": [8.1, 8.8, 8.5, 8.3, 8.3, 8.5, 7.
    
